package it.pjay.knowledgeshow

import android.content.ContentValues
import android.content.Context
import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import android.database.sqlite.SQLiteOpenHelper

class DatabaseHelper(context: Context) :
    SQLiteOpenHelper(context, DATABASE_NAME, null, DATABASE_VERSION) {
    companion object {
        private const val DATABASE_NAME = "knowledgeshow"
        private const val DATABASE_VERSION = 3
        private const val TABLE_NAME = "questions"
        private const val COLUMN_ID = "_id"
        private const val COLUMN_CATEGORY = "category"
        private const val COLUMN_QUESTION = "question"
        private const val COLUMN_ANSWER = "answer"
        private const val COLUMN_FACT = "fact"
    }

    override fun onCreate(db: SQLiteDatabase?) {
        val createTable =
            "CREATE TABLE $TABLE_NAME ($COLUMN_ID INTEGER PRIMARY KEY AUTOINCREMENT, $COLUMN_CATEGORY TEXT, $COLUMN_QUESTION TEXT, $COLUMN_ANSWER TEXT, $COLUMN_FACT TEXT)"
        db?.execSQL(createTable)
        fillDatabase(db)
    }

    override fun onUpgrade(db: SQLiteDatabase?, oldVersion: Int, newVersion: Int) {
        db?.execSQL("DROP TABLE IF EXISTS $TABLE_NAME")
        onCreate(db)
    }
    fun insertData(db: SQLiteDatabase?, category: String, question: String, answer: String, fact: String ) {
//        val db = this.writableDatabase
        val values = ContentValues().apply {
            put(COLUMN_CATEGORY, category)
            put(COLUMN_QUESTION, question)
            put(COLUMN_ANSWER, answer)
            put(COLUMN_FACT, "randomfact")
        }
        if (db != null) {
            db.insert(TABLE_NAME, null, values)
        }
        
    }
    fun getRandomEntry(): QuestionEntry? {
        val db = this.readableDatabase
        val cursor: Cursor =
            db.rawQuery("SELECT * FROM $TABLE_NAME ORDER BY RANDOM() LIMIT 1", null)
        var questionEntry: QuestionEntry? = null
        if (cursor.moveToFirst()) {
            val id = cursor.getInt(cursor.getColumnIndex(COLUMN_ID))
            val category = cursor.getString(cursor.getColumnIndex(COLUMN_CATEGORY))
            val question = cursor.getString(cursor.getColumnIndex(COLUMN_QUESTION))
            val answer = cursor.getString(cursor.getColumnIndex(COLUMN_ANSWER))
            val fact = cursor.getString(cursor.getColumnIndex(COLUMN_FACT))
            questionEntry = QuestionEntry(id, category, question, answer, fact)
        }
        cursor.close()
        return questionEntry
    }

    fun fillDatabase(db: SQLiteDatabase?){
        insertData(db,"Historia", "Który władca założył stolicę Cesarstwa Niemieckiego w Berlinie?", "Wilhelm I", "ciekawostka 1")
        insertData(db,"Historia", "Który kraj był pierwszym, który uznał niepodległość Stanów Zjednoczonych?", "Maroko", "ciekawostka 2")
        insertData(db,"Geografia", "Które państwo ma najwięcej jezior?", "Kanada", "ciekawostka 4")
        insertData(db,"Geografia", "Który kontynent jest największy pod względem liczby ludności?", "Azja", "ciekawostka 5")
        insertData(db,"Biologia", "Jak nazywa się gruczoł odpowiedzialny za wydzielanie insuliny?", "Trzustka", "ciekawostka 7")
        insertData(db,"Biologia", "Który pierwiastek jest składnikiem hemoglobiny?", "Żelazo", "ciekawostka 8")
        insertData(db, "Biologia", "Jak nazywa się największy układ nerwowy u człowieka?", "Ośrodkowy Układ Nerwowy", "ciekawostka 9")
        insertData(db, "Matematyka", "Jaki jest wynik mnożenia 111 przez 111?", "12321", "ciekawostka 10")
        insertData(db, "Matematyka", "Ile wynosi pierwiastek kwadratowy z 121?", "11", "ciekawostka 11")
        insertData(db, "Matematyka", "Jak nazywa się linia przecinająca oś symetrii paraboli?", "Oś równoległa", "ciekawostka 12")
        insertData(db, "Sport", "Która drużyna wygrała najwięcej Super Bowlów w historii NFL?", "New England Patriots", "ciekawostka 13")
        insertData(db, "Sport", "Który klub piłkarski jest rekordzistą pod względem liczby zdobytych Lig Mistrzów?", "Real Madryt", "ciekawostka 15")
        insertData(db, "Film", "Kto zagrał główną rolę w filmie \"Rocky\"?", "Sylvester Stallone", "ciekawostka 16")
        insertData(db, "filmy", "Kto zagrał postać Forresta Gumpa w filmie o tym samym tytule?", "Tom Hanks", "ciekawostka 5")
        insertData(db, "filmy", "W jakim roku miał swoją premierę film Pulp Fiction?", "1994", "ciekawostka 6")
        insertData(db, "sport", "Z jakiego kraju pochodzi tenisistka Naomi Osaka?", "Japonia", "ciekawostka 7")
        insertData(db, "sport", "Ile złotych medali olimpijskich zdobył Usain Bolt?", "8", "ciekawostka 8")
        insertData(db, "sport", "Jakie drużyny rywalizują w meczu El Clásico?", "FC Barcelona i Real Madryt", "ciekawostka 9")
        insertData(db, "historia", "Który rok uważany jest za początek II wojny światowej?", "1939", "ciekawostka 10")
        insertData(db, "historia", "W którym roku podpisano traktat wersalski kończący I wojnę światową?", "1919", "ciekawostka 12")
        insertData(db, "nauka", "Jaka jest najmniejsza cząstka pierwiastka?", "Atom", "ciekawostka 13")
        insertData(db, "nauka", "Co oznacza skrót DNA?", "Kwas deoksyrybonukleinowy", "ciekawostka 14")
        insertData(db, "nauka", "Ile wynosi liczba pi?", "3,14", "ciekawostka 15")
        insertData(db, "muzyka", "Jak nazywał się ostatni studyjny album zespołu The Beatles?", "Let It Be", "ciekawostka 16")
        insertData(db, "muzyka", "Która z piosenek Madonny zdobyła najwięcej nagród Grammy?", "Ray of Light", "ciekawostka 17")
        insertData(db, "muzyka", "Który z zespołów wydał album 'The Dark Side of the Moon'?", "Pink Floyd", "ciekawostka 18")
        insertData(db, "geografia", "Jaka jest stolica Australii?", "Canberra", "ciekawostka 19")
        insertData(db, "geografia", "Które miasto jest stolicą Rosji?", "Moskwa", "ciekawostka 20")
        insertData(db, "geografia", "Które państwo ma najwięcej ludności na świecie?", "Chiny", "ciekawostka 21")

        insertData(db, "Kategoria ogólna", "Jak nazywa się publiczne popisy kowbojów we władaniu lasem i w jeździe na koniach i bykach?", "Rodeo", "ciekawostka 1")
        insertData(db, "Literatura", "Który powieściowy bohater swoją wybrankę nazwał Dulcyneum?", "John Cichot, bohater powieści Cervantesa", "ciekawostka 1")
        insertData(db, "Transport", "Jaki kolor ma strzałka na sygnalizatorze świetlnym, zezwalająca na skręt w prawo?", "Zielona", "ciekawostka 1")
        insertData(db, "Anatomia", "W której części ciała człowieka znajduje się kość potyliczna?", "W głowie, w czaszce", "ciekawostka 1")
        insertData(db, "Historia", "Od ataku na którą bazę wojskową zaczęła się wojna między Japonią a Stanami Zjednoczonymi w czasie drugiej wojny światowej?", "Pearl Harbor", "ciekawostka 1")
        insertData(db, "Nauka", "Czy neutrony mają ładunek dodatni?", "Nie", "ciekawostka 1")
        insertData(db, "Geografia", "Jak nazywają się wielkie fale morskie wywołane podwodnymi trzęsieniami ziemi albo wybuchami wulkanów?", "Fale tsunami", "ciekawostka 1")
        insertData(db, "Religia", "Ilu uczniom ukazał się Jezus w dniu zmartwychwstania w drodze do Emaus?", "Dwóm", "ciekawostka 1")
        insertData(db, "Geografia", "Nad którym morzem leży port w Rotterdamie?", "Nad Morzem Północnym", "ciekawostka 1")
        insertData(db, "Rower", "Które koło w rowerze było większe, przednie czy tylne?", "Tylne", "ciekawostka 1")
        insertData(db, "Sport", "Proszę rozwinąć skrót PZPN.", "Polski Związek Piłki Nożnej", "ciekawostka 1")
        insertData(db, "Nauka", "Może być przemienny, stały, wielofazowy, jednofazowy. O czym mowa?", "Prąd elektryczny", "ciekawostka 1")
        insertData(db, "Literatura", "Jak miał na imię chilejski poeta Neruda?", "Pablo (Paweł) Neruda", "ciekawostka 1")
        insertData(db, "Język", "Czy hiobowa wieść to jest dobra wiadomość?", "Nie", "ciekawostka 1")
        insertData(db, "Architektura", "Jak z hiszpańskiego nazywa się niewielki dziedziniec wewnątrz domu albo pałacu?", "Patio", "ciekawostka 1")
        insertData(db, "Geografia Polski", "Proszę podać nazwę prawego dopływu Wisły, który płynie przez Pieniny.", "Dunajec", "ciekawostka 1")
        insertData(db, "Zoologia", "Skrzek. To jaja płazów, gadów czy ryb?", "Płazów", "ciekawostka 1")
        insertData(db, "Motoryzacja", "Pojazdy mechaniczne. Którą liczbą oznaczony był model Fiata nazywanego w Polsce maluchem?", "126", "ciekawostka 1")
        insertData(db, "Matematyka", "Czy w matematyce istnieją liczby urojone?", "Tak", "ciekawostka 1")
        insertData(db, "Język polski", "Jak nazywa się ostatni przypadek polskiej deklinacji?", "Wołacz", "ciekawostka 1")
        insertData(db, "Sport", "W której dyscyplinie sportu Justyna Kowalczyk zdobyła dwa złote medale olimpijskie?", "Biegi narciarskie", "ciekawostka 1")
        insertData(db, "Muzyka", "Klasycy wiedeńscy to określenie trzech kompozytorów z przełomu XVIII i XIX wieku. Proszę wymienić dwóch spośród nich.", "Haydn i Beethoven", "ciekawostka 1")
        insertData(db, "Matematyka", "Objętość walca jest iloczynem pola podstawy i czego?", "Wysokości tego walca", "ciekawostka 1")
        insertData(db, "Prawo", "Z ilu izb składa się polski parlament?", "Z dwóch", "ciekawostka 1")
        insertData(db, "Geografia Polski", "W którym mieście jest Droga Królewska wiodąca od Bramy Wyżynnej przez ulicę Długą i Długi Targ aż do Zielonej Bramy?", "Gdańsk", "ciekawostka 1")
        insertData(db, "Służby specjalne", "Schinbett. W którym państwie tak nazywają się służby specjalne?", "Izrael", "ciekawostka 1")
        insertData(db, "Służby specjalne", "Mossad. W którym państwie tak nazywają się służby specjalne?", "Izrael", "ciekawostka 1")
        insertData(db, "Historia", "Kto panował dłużej? Królowa Wielkiej Brytanii Wiktoria czy Cesarz Austrii Franciszek Józef I?", "Franciszek Józef I", "ciekawostka 1")
        insertData(db, "Botanika", "Bukiew. Bukiew to owoce którego drzewa?", "Buku", "ciekawostka 1")
        insertData(db, "Film", "Z którego filmu pochodzi \"Deszczowa piosenka\"?", "Deszczowa Piosenka", "ciekawostka 1")

        insertData(db, "Historia Polski", "Kopalniami którego minerału zarządzał Sebastian Lubomirski w końcu XVI wieku?", "Soli", "ciekawostka 1")
        insertData(db, "Architektura", "Na ile części podzielone jest pionowo tak zwane Okno Weneckie?", "Trzy", "ciekawostka 1")
        insertData(db, "Parki narodowe", "W którym województwie utworzono Poleski Park Narodowy?", "Lubelskie", "ciekawostka 1")
        insertData(db, "Kultura", "Czy tambur to jest nazwa batuty Tambur Majora?", "Nie", "ciekawostka 1")
        insertData(db, "Kabaret", "W którym kabarecie występują Jadwiga i Dariusz Basińscy?", "Mumio", "ciekawostka 1")
        insertData(db, "Zoologia", "Czy żako to ptak czy ssak?", "Ptak", "ciekawostka 1")
        insertData(db, "Geografia", "Nad którą cieśniną góruje most drogowo-kolejowy sułtana Selima Groźnego?", "Bosfor", "ciekawostka 1")
        insertData(db, "Kościoły i religie", "Jak w kościele katolickim nazywa się duchowny zajmujący się wysuwaniem zarzutów w procesie beatyfikacyjnym albo kanonizacyjnym?", "Adwokat diabła", "ciekawostka 1")
        insertData(db, "Literatura starożytna", "Safona to poetka grecka czy rzymska?", "Grecka", "ciekawostka 1")
        insertData(db, "Anatomia człowieka", "Zawiasowy, kłykciowy, siodełkowy to typy stawów czy nazwy mięśni szkieletowych?", "Typy stawów", "ciekawostka 1")
        insertData(db, "Pieniądze", "Czy banknoty 10, 20 i 50 złotych, polskie banknoty, mają takie same wymiary?", "Nie", "ciekawostka 1")
        insertData(db, "Języki", "Jak z greki nazywa się człowiek władający wieloma językami?", "Poliglota", "ciekawostka 1")
        insertData(db, "Powiedzenia", "Żyje z dnia na dzień ten kto nie troszczy się o przyszłość, czy też ten kto ciężko pracuje?", "Ten kto nie troszczy się o przyszłość", "ciekawostka 1")
        insertData(db, "Komiks", "Jak nazywa się Tęgi Gal, najbliższy przyjaciel Asterixa, tytułowego bohatera komiksów i filmów?", "Obelix", "ciekawostka 1")

        insertData(db, "Parapsychologia", "Jak nazywa się zdolność poruszania przedmiotów materialnych na odległość?", "Telekineza", "ciekawostka 1")
        insertData(db, "Medycyna", "W którym wieku odkryto insulinę, co spowodowało przełom w leczeniu cukrzycy?", "W 20. (Poprawna odpowiedź: W 1922 roku)", "ciekawostka 1")
        insertData(db, "Literatura", "Kto napisał Eneidę, rzymską epopeję narodową?", "Wergiliusz", "ciekawostka 1")
        insertData(db, "Kategoria ogólna", "Czy Wernyhora z obrazu Jana Matejki trzyma w ręku instrument muzyczny?", "Nie", "ciekawostka 1")
        insertData(db, "Język polski", "Jak brzmi stopień wyższy przy słowie 'dobrze'?", "Lepiej", "ciekawostka 1")
        insertData(db, "Geografia", "Która wyspa Dodekanezu na Morzu Egejskim jest największa?", "Wyspa Rodos", "ciekawostka 1")
        insertData(db, "Teatr", "Gogo i Didi to postaci z której sztuki Samuela Becketta?", "Czekając na Godota", "ciekawostka 1")
        insertData(db, "Wojsko", "Czyje imię nosi Akademia Marynarki Wojennej w Gdyni?", "Bohaterów Westerplatte", "ciekawostka 1")
        insertData(db, "Językoznawstwo", "Co oznacza łacińskie słowo 'sanatio'? Od którego pochodzi polski wyraz 'sanacja'?", "Uzdrowienie", "ciekawostka 1")
        insertData(db, "Polityka", "Ilu członków stałych liczy Rada Bezpieczeństwa ONZ?", "5", "ciekawostka 1")
        insertData(db, "Biologia", "Prokariota. Posiadają czy nie mają jądra komórkowego?", "Nie", "ciekawostka 1")
        insertData(db, "Cytaty", "'W czasie wojny milczą prawa.' Czyje to słowa?", "Cycerona", "ciekawostka 1")
        insertData(db, "Film", "Jak nazywa się brytyjska aktorka nagrodzona w tym roku Oscarem dla najlepszej aktorki pierwszoplanowej?", "Olivia Colman", "ciekawostka 1")
        insertData(db, "Geografia", "Jak brzmi akronim nazw trzech państw położonych na obszarze historycznych Niderlandów?", "Benelux", "ciekawostka 1")
        insertData(db, "Filozofia", "Indyferencja to obojętność czy zaangażowanie i działanie?", "Obojętność", "ciekawostka 1")

        insertData(db, "Literatura", "Który polski poeta, wielki miłośnik Tatr i folkloru góralskiego jest autorem słów tej pieśni?", "Kazimierz Przerwa-Tetmajer", "ciekawostka 1")
        insertData(db, "Geografia", "Które miasto Afryki ma najwięcej mieszkańców?", "Kair", "ciekawostka 1")
        insertData(db, "Sztuka", "Która dziedzina sztuki była domeną francuza Eugeniusza de la Croix?", "Malarstwo", "ciekawostka 1")
        insertData(db, "Historia", "Które odznaczenie ustanowił król Stanisław August Poniatowski po zwycięskiej bitwie pod Zieleńcami w 1792 roku?", "Virtuti Militari", "ciekawostka 1")
        insertData(db, "Kategoria ogólna", "Proszę dokończyć przysłowie. \"Nie czyń drugiemu...\"", "Co tobie niemiłe", "ciekawostka 1")
        insertData(db, "Historia", "Ilu papieży nosiło imię Urban? Jeden czy ośmiu?", "Ośmiu", "ciekawostka 1")
        insertData(db, "Historia", "Czy pułkownik Jan Kozietulski zginął w bitwie pod Somosierrą?", "Nie", "ciekawostka 1")
        insertData(db, "Historia", "W którym państwie panował zbrodniczy reżim Czerwonych Kmerów?", "W Kambodży", "ciekawostka 1")
        insertData(db, "Geografia", "Na którym oceanie występuje prąd morski El Niño?", "Na Oceanie Spokojnym", "ciekawostka 1")
        insertData(db, "Film", "\"Klient w krawacie jest mniej awanturujący się.\" To cytat z której polskiej komedii?", "\"Miś\" Stanisława Barei", "ciekawostka 1")
        insertData(db, "Historia", "Z ilu sztuk bydła składana była bogom ofiara nazywana w Grecji starożytnej Hekatombą?", "Ze stu sztuk bydła", "ciekawostka 1")
        insertData(db, "Wojsko", "Jak nazywa się w wojskach lotniczych jednostka składająca się z dwóch trzech eskadr?", "Dywizjon", "ciekawostka 1")
        insertData(db, "Literatura", "Jak brzmi tytuł dwunastej księgi pana Tadeusza?", "\"Kochajmy się\"", "ciekawostka 1")
        insertData(db, "Historia", "Dyplomatą którego państwa był Raoul Wallenberg, który w czasie drugiej wojny światowej przyczynił się do uratowania tysięcy Żydów na Węgrzech?", "Szwedzkim dyplomatą.", "ciekawostka 1")

        insertData(db, "Literatura", "Basia, Helena czy Oleńka? Która z wymienionych postaci jest bohaterką powieści 'Ogniem i Mieczem'?", "Helena", "ciekawostka 1")
        insertData(db, "Fizyka", "Środkiem czego jest barycentrum?", "Środkiem ciężkości", "ciekawostka 1")
        insertData(db, "Geografia", "Z jakich kolorów składa się flaga Estonii?", "Z białego, czarnego i niebieskiego", "ciekawostka 1")
        insertData(db, "Historia", "W którym województwie leżą Płowce, gdzie w 1331 roku rozegrała się bitwa Polaków z wojskami krzyżackimi?", "Kujawsko-Pomorskie", "ciekawostka 1")
        insertData(db, "Teatr", "Jak nazywał się placyk na przedzie proscenium, na którym występował chór w starożytnym Teatrze Greckim?", "Orchestra", "ciekawostka 1")
        insertData(db, "Muzyka", "Co znaczy dosłownie włoski termin 'libretto'?", "Książeczka", "ciekawostka 1")
        insertData(db, "Biologia", "Czy grejpfrut jest cytrusem?", "Tak", "ciekawostka 1")
        insertData(db, "Chemia", "Z atomów którego pierwiastka zbudowany jest grafen?", "Z węgla", "ciekawostka 1")
        insertData(db, "Sport", "Telemark. To określenie pochodzące z której dyscypliny sportowej?", "Ze skoków narciarskich", "ciekawostka 1")
        insertData(db, "Historia", "Jak nazywał się ostatni król z dynastii Piastów?", "Kazimierz Wielki", "ciekawostka 1")
        insertData(db, "Literatura", "W powieści 'Pinokio' stary Gepetto sam zrobił tytułowego bohatera. Z czego go zrobił?", "Z drewna", "ciekawostka 1")
        insertData(db, "Żegluga", "Biała flota to określenie okrętów wojennych czy statków pasażerskich?", "Statków pasażerskich", "ciekawostka 1")
        insertData(db, "Historia", "Jak nazywali się szlachetnie urodzeni rycerze w feudalnej Japonii?", "Samuraje", "ciekawostka 1")
        insertData(db, "Gramatyka", "Aktivum to strona czynna czy bierna w czasownikach?", "Strona czynna", "ciekawostka 1")

        insertData(db, "Mitologia", "Jak nazywali się dwaj bracia Zeusa? Bóg Morza i Bóg Świata Podziemnego?", "Posejdon i Hades", "ciekawostka 1")
        insertData(db, "Moda", "Ramoneska. Ramoneska to nazwa ptaka zamieszkującego lasy w dorzeczu Amazonki, czy też rodzaj kurtki skórzanej zapinanej na błyskawiczny zamek?", "Rodzaj kurtki skórzanej", "ciekawostka 1")
        insertData(db, "Fizyka", "Jak nazywa się nauka o ruchu pocisków?", "Balistyka", "ciekawostka 1")
        insertData(db, "Historia", "Historia, częścią którego państwa w czasach Napoleona Bonapartego było Monaco?", "Francji", "ciekawostka 1")
        insertData(db, "Skróty", "Proszę rozwinąć skrót nazwy państwowej instytucji IMGW.", "Instytut Meteorologii i Gospodarki Wodnej", "ciekawostka 1")
        insertData(db, "Astronomia", "Astronomia. Która planeta Układu Słonecznego krąży najbliżej Słońca?", "Merkury", "ciekawostka 1")
        insertData(db, "Przysłowia", "Przysłowia. Dolanie oliwy do ognia pogorszy sytuację, czy rozwiąże problem?", "Pogorszy sytuację", "ciekawostka 1")
        insertData(db, "Literatura polska", "Literatura polska, które góry opisywał w swoich utworach Kazimierz Przerwa-Tetmajer?", "Tatry", "ciekawostka 1")
        insertData(db, "Broń", "Co przechowuje się w kołczanie?", "Strzały", "ciekawostka 1")
        insertData(db, "Historia", "W którym państwie pierwszym prezydentem był George Washington?", "Stanach Zjednoczonych Ameryki", "ciekawostka 1")
        insertData(db, "Język angielski", "Co oznacza angielskie wyrażenie 'happy end'?", "Szczęśliwe zakończenie", "ciekawostka 1")
        insertData(db, "Literatura polska", "Literatura polska, w której powieści Witolda Gombrowicza według słów ucznia Słowacki nie zachwycał?", "'Ferdydurke'", "ciekawostka 1")

        insertData(db, "Historia", "W którym roku został podpisany traktat wersalski?", "W 1919 roku", "ciekawostka 1")
        insertData(db, "Osobowości", "Jak nazywała się kobieta, która dwukrotnie dostała Nagrodę Nobla?", "Maria Gieliszkodowska", "ciekawostka 1")
        insertData(db, "Genealogia", "Czy publicysta i polityk Stanisław Cat-Mackiewicz i pisarz Józef Mackiewicz byli spokrewnieni?", "Tak", "ciekawostka 1")
        insertData(db, "Geografia", "W którym europejskim państwie wznoszą się góry pieprzowe?", "Polsce", "ciekawostka 1")
        insertData(db, "Waluty świata", "Afgani to jednostka monetarna którego azjatyckiego państwa?", "Afganistanu", "ciekawostka 1")
        insertData(db, "Historia", "Jak nazywa się miasto we Francji, gdzie była siedziba kolaboracyjnego rządu Philippe Petain?", "Vichy", "ciekawostka 1")
        insertData(db, "Literatura polska", "Które czarnoleskie drzewo było tematem fraszek Jana Kochanowskiego?", "Lipa", "ciekawostka 1")
        insertData(db, "Gry", "Które bierki rozpoczynają grę w szachy? Białe czy czarne?", "Białe", "ciekawostka 1")
        insertData(db, "Muzyka", "Do słów wiersza którego poety Franciszek Schubert skomponował tę pieśń znaną jako Król Elfów?", "Goethego", "ciekawostka 1")
        insertData(db, "Geografia", "Jak nazywa się niemiecki kraj związkowy, którego stolicą jest Monachium?", "Bawaria", "ciekawostka 1")
        insertData(db, "Religia", "Tales to szal zakładany podczas modlitwy przez wyznawców której religii?", "Judaizmu", "ciekawostka 1")
        insertData(db, "Historia", "Dynastia Andegawenów panowała w Polsce przed czy po Jagiellonach?", "Przed", "ciekawostka 1")
        insertData(db, "Zoologia", "Czy łosoś może żyć w słonych wodach?", "Tak", "ciekawostka 1")

        insertData(db, "Polityka", "Parlament którego państwa ma siedzibę w Belgradzie?", "Serbii", "ciekawostka 1")
        insertData(db, "Literatura polska", "Kto jest autorem wiersza dla dzieci Tańcowała igła z nitką?", "Brzechwa", "ciekawostka 1")
        insertData(db, "Religia", "Czy święty Marek Ewangelista był apostołem Jezusa?", "Nie", "ciekawostka 1")
        insertData(db, "Polskie miasta", "Czy warszawska Starówka jest wpisana na listę światowego dziedzictwa UNESCO?", "Tak", "ciekawostka 1")
        insertData(db, "Miary i wagi", "Był w Polsce jednostką długości, ciężaru czy objętości?", "Objętości", "ciekawostka 1")
        insertData(db, "Ekologia", "Proszę wymienić jedno z dwóch państw emitujących najwięcej dwutlenku węgla na świecie.", "Chiny", "ciekawostka 1")
        insertData(db, "Zoologia", "Czy bóbr jest drapieżnikiem, gryzoniem czy przeżuwaczem?", "Gryzoniem", "ciekawostka 1")
        insertData(db, "Muzyka", "W którym stuleciu Jerzy Fryderyk Hendel skomponował dzieło Muzyka na wodzie.", "XVIII wieku", "ciekawostka 1")
        insertData(db, "Historia", "Kto w 1430 roku został wielkim księciem litewskim po śmierci Witolda?", "Świdrygieło", "ciekawostka 1")
        insertData(db, "Prasa", "Jak brzmi pełny tytuł wydawanego w II Rzeczypospolitej dziennika zwanego potocznie IKAC-em?", "Ilustrowany kurier codzienny", "ciekawostka 1")
        insertData(db, "Literatura polska", "O psy której rasy toczy się spór asesora z rejentem w panu Tadeuszu Mickiewicza?", "O wyżły", "ciekawostka 1")
        insertData(db, "Film polski", "Kto skomponował muzykę do filmów Ogniem i Mieczem, Stara baśń, W pustyni i w puszczy?", "Krzesimir Dębski", "ciekawostka 1")
        insertData(db, "Geografia", "W którym mieście ma siedzibę Europejski Bank Centralny?", "We Frankfurcie nad Menem", "ciekawostka 1")
        insertData(db, "Religia", "Jakie imiona nosili trzej synowie Noego?", "Jafet, Ham i Sem", "ciekawostka 1")
        insertData(db, "Historia", "Unia Gospodarcza Beneluxu powstała w którym wieku?", "W piętnastym", "ciekawostka 1")

        insertData(db, "Historia średniowiecza", "Z której dynastii pochodził pierwszy król Węgier, Stefan I?", "Z Arpadów", "ciekawostka 1")
        insertData(db, "Organizacje międzynarodowe", "Kto jest sekretarzem generalnym NATO? Czy Jens Stoltenberg, czy Anders Fokrasmusen?", "Jens Stoltenberg", "ciekawostka 1")
        insertData(db, "Fizyka", "W czasie ruchu obrotowego Ziemi większą prędkość kątową ma punkt leżący na równiku, czy na kole podbiegunowym?", "Punkt leżący na równiku", "ciekawostka 1")
        insertData(db, "Sztuka", "Proszę podać imię polskiej malarki o nazwisku Berezowska.", "Maja", "ciekawostka 1")
        insertData(db, "Historia wojskowości", "Jak nazywały się oddziały piechoty francuskiej utworzone w Algierii w 1831 roku? W Armii francuskiej istniały do II wojny światowej.", "Żuławy", "ciekawostka 1")
        insertData(db, "Literatura polska", "Gdzie miało miejsce tytułowe porwanie w powieści dla dzieci Wojciecha Żukrowskiego?", "W Tiutjurlistanie", "ciekawostka 1")
        insertData(db, "Astronomia", "Ślimak. To nazwa gwiazdozbioru, czy mgławica planetarna?", "Mgławica planetarna", "ciekawostka 1")
        insertData(db, "Muzyka", "Który kompozytor rosyjski jest twórcą opery Słowik według libretta opartego na baśni Andersena?", "Igor Strawiński", "ciekawostka 1")
        insertData(db, "Religia", "Którym w kolejności miesiącem muzułmańskiego kalendarza jest Ramadan?", "Ósmym", "ciekawostka 1")
        insertData(db, "Historia", "W którym mieście Józef Stalin, Franklin Delano Roosevelt i Winston Churchill spotkali się na konferencji w 1943 roku?", "Teheran", "ciekawostka 1")
        insertData(db, "Historia wojskowości", "Jak dawniej nazywano wojskowy szpital polowy organizowany doraźnie podczas działań wojennych?", "Lazaret", "ciekawostka 1")
        insertData(db, "Profesje", "Stolarz, artysta wyrabiający artystyczne meble fornirowane i intarsjowane.", "Szneczarz Ebenista", "ciekawostka 1")
        insertData(db, "Film", "Instytut filmowy którego państwa przyznaje nagrody Złote Żuki?", "Szwedzki Instytut Filmowy", "ciekawostka 1")
        insertData(db, "Kulinaria", "Przy której ulicy w Krakowie czeka na gości kawiarnia Jana Michalika?", "Przy ulicy Floriańskiej pod czterdziestym piątym numerem.", "ciekawostka 1")
        insertData(db, "Historia", "Który generał niemiecki w czasie II wojny światowej podpisał wręcz 7 maja 45 roku akt bezwarunkowej kapitulacji Wehrmachtu?", "Alfred Jodl", "ciekawostka 1")

        insertData(db, "Fizjologia człowieka", "Fibrynogen. To białko, enzym trawienny czy hormon nadnercza?", "Białko osocza krwi", "ciekawostka 1")
        insertData(db, "Waluty", "Jak nazywa się waluta Mołdawii?", "Lej mołdawski", "ciekawostka 1")
        insertData(db, "Kościoły i religie", "Jak w buddyzmie i hinduizmie, nazywa się suma uczynków człowieka, decydująca o charakterze następnego wcielenia w reinkarnacji.", "Karma", "ciekawostka 1")
        insertData(db, "Historia", "W którym cesarstwie rządy sprawowała do 802 roku Irena Święta Prawosławna?", "Cesarstwo bizantyjskie", "ciekawostka 1")
        insertData(db, "Literatura polska", "Jakie imiona nosił pisarz Niemcewicz?", "Julian Ursyn", "ciekawostka 1")
        insertData(db, "Ekonomia", "Które wyrażenie oznacza stopniowe wzrastanie? Progresja, recesja czy regresja?", "Progresja", "ciekawostka 1")
        insertData(db, "Wędkarstwo", "Jak nazywa się metoda łowienia ryb przez zarzucanie na dużą odległość przynęty i powolne przyciąganie jej kołowrotkiem?", "Spinning", "ciekawostka 1")
        insertData(db, "Historia", "Czy przed II wojną światową istniało niepodległe państwo Izrael?", "Nie, nie istniało. Powstało w 1948 roku na terenie Palestyny.", "ciekawostka 1")
        insertData(db, "Uczeni", "Z którego państwa pochodził Aleksandr Popow, urodzony w połowie XIX wieku pionier radiotechniki?", "Rosja", "ciekawostka 1")
        insertData(db, "Chemia", "Ile atomów zawiera jedna cząsteczka wody?", "Trzy atomy Dwa wodoru i jeden tlenu.", "ciekawostka 1")
        insertData(db, "Językoznawstwo", "Wtórnik to oryginał czy kopia?", "Kopia", "ciekawostka 1")
        insertData(db, "Powiedzenia", "Według powiedzenia za co chwyta się byka, jeśli ktoś energicznie przystępuje do rzeczy?", "Za rogi", "ciekawostka 1")
        insertData(db, "Geografia", "Czy stolica Turcji, Ankara, jest portem?", "Nie, nie jest. Leży w głębi lądu.", "ciekawostka 1")

        insertData(db, "Kuchnia", "Które warzywo stanowi podstawę zupy zwanej chłodnikiem litewskim?", "Burak", "ciekawostka 1")
        insertData(db, "Literatura dziecięca", "W wyliczance lml dudki. Jaki jest gospodarz?", "Malutki", "ciekawostka 1")
        insertData(db, "Historia", "W którym wieku żył Andrzej Frycz-Modrzewski?", "W 16", "ciekawostka 1")
        insertData(db, "Druga wojna światowa", "Czy Herman Goering był sądzony w procesie norymberskim?", "Był i został skazany na karę śmierci, ale w 46 roku popełnił samobójstwo", "ciekawostka 1")
        insertData(db, "Historia", "Jakie imię nosił biskup krakowski kanonizowany w 1253 roku?", "Stanisław", "ciekawostka 1")
        insertData(db, "Literatura", "Kto od śmierci Jerzego Giedroycia pełni obowiązki redaktora paryskiej kultury?", "Kultura", "ciekawostka 1")
        insertData(db, "Powiedzenia", "Dawać komuś coś, czego ten nie potrafi docenić, to rzucać perły przed...", "Wieprza", "ciekawostka 1")
        insertData(db, "Muzyka", "Jakiego życia życzą członkowie zespołu Kombi w jednej ze swoich piosenek?", "Słodkiego, długiego", "ciekawostka 1")
        insertData(db, "Moda i ubiór", "Z którego państwa pochodzi strój kobiecy zwany mantylą?", "Hiszpanii", "ciekawostka 1")
        insertData(db, "Mineralogia", "Sard, którego nazwa pochodzi od stolicy starożytnej Lidii? To jest lniany materiał czy minerał?", "To jest minerał", "ciekawostka 1")
        insertData(db, "Żegluga", "Na którym kanale nie ma śluz? Na Suezskim, Kilońskim czy Panamskim?", "Na kanale Suezskim nie ma śluz", "ciekawostka 1")
        insertData(db, "Językoznawstwo", "Co znaczy łacińskie in secula seculorum?", "Na wieki wieków", "ciekawostka 1")
        insertData(db, "Literatura", "Który pisarz science fiction wymyślił twory zwane sepulkami?", "Lem. Stanisław Lem", "ciekawostka 1")
        insertData(db, "Sport", "Jaki sport uprawiali Kazimierz Paździor i Leszek Drogosz?", "Boks", "ciekawostka 1")

        insertData(db, "Sztuka filmowa", "Ile razy aktorka Meryl Streep zdobyła nagrodę Oscara?", "Trzy razy", "ciekawostka 1")
        insertData(db, "Historia", "Jak miał na imię skarga kaznodzieja przedstawiciel polskiej kontrreformacji?", "Piotr", "ciekawostka 1")
        insertData(db, "Słownictwo", "Słowo, o które pytam jest związane ze świeczką, a czasem oznacza coś nieudanego. Które to słowo?", "Knot", "ciekawostka 1")
        insertData(db, "Kultura", "Którego dnia roku obchodzona jest Barbórka, święto górników?", "4 grudnia", "ciekawostka 1")
        insertData(db, "Geografia", "Do którego morza ma dostęp Gruzja?", "Do Morza Czarnego", "ciekawostka 1")
        insertData(db, "Sztuka", "Poczet królów i książąt polskich Jana Matejki to cykl wizerunków w wersji czarno-białej czy w wersji barwnej?", "W wersji czarno-białej", "ciekawostka 1")
        insertData(db, "Geografia", "Jaki jest język urzędowy w Republice San Marino?", "Włoski", "ciekawostka 1")
        insertData(db, "Matematyka", "Ile wynosi suma kątów wewnętrznych w trapezie?", "360 stopni", "ciekawostka 1")
        insertData(db, "Medycyna", "W którym mieście działa Instytut Centrum Zdrowia Matki Polki?", "W Łodzi", "ciekawostka 1")
        insertData(db, "Kuchnia", "Pęczak to kasza ze zbożowych ziaren całych czy pokruszonych?", "Z całych ziaren", "ciekawostka 1")
        insertData(db, "Fizyka", "Której wielkości fizycznej dotyczą skale Kelwina i Fahrenheita?", "Temperatury", "ciekawostka 1")
        insertData(db, "Botanika", "Przebiśniegi kwitną wiosną czy późną jesienią?", "Wiosną", "ciekawostka 1")
        insertData(db, "Geografia", "Jak nazywa się najludniejsze miasto nad rzeką Wartą?", "Poznań", "ciekawostka 1")
        insertData(db, "Historia", "Kto sprawował funkcję premiera Wielkiej Brytanii, kiedy na tronie zasiadła Elżbieta II?", "Winston Churchill", "ciekawostka 1")

        insertData(db, "Chemia", "Który pierwiastek ma symbol chemiczny He?", "Hel", "ciekawostka 1")
        insertData(db, "Astronomia", "W ile dni światło pokonuje dystans jednego roku świetlnego?", "365 dni", "ciekawostka 1")
        insertData(db, "Biżuteria", "Cyrkonie to kamienie szlachetne?", "Nie, to są sztuczne kamienie imitujące diament", "ciekawostka 1")
        insertData(db, "Biologia", "Jakim organem oddychają ryby?", "Skrzelami", "ciekawostka 1")
        insertData(db, "Idiomy", "Jeśli zaczynamy od kogoś więcej wymagać, to przekazujemy mu pałeczkę czy podnosimy mu poprzeczkę?", "Podnosimy mu poprzeczkę", "ciekawostka 1")
        insertData(db, "Moda", "Rybaczki - która to część garderoby?", "To są spodnie", "ciekawostka 1")
        insertData(db, "Literatura starożytna", "W którym dziele Homer opisał wędrówkę Odyseusza?", "W Odysei", "ciekawostka 1")
        insertData(db, "Transport", "Droga żelazna to dawne określenie którego systemu transportu?", "Kolei", "ciekawostka 1")
        insertData(db, "Historia żeglugi", "Galera to dawny typ okrętu. Co było głównym napędem galery?", "Wiosłowanie, wieślarze", "ciekawostka 1")
        insertData(db, "Mitologia", "Którego tytana Zeus kazał przykuć do skały Kaukazu?", "Prometeusza", "ciekawostka 1")
        insertData(db, "Boks", "Jaki przydomek nosił Felix Stamm, wieloletni trener polskich bokserów?", "Papa Stamm", "ciekawostka 1")
        insertData(db, "Motoryzacja", "Jakim trzyliterowym skrótem jest oznaczana na stacjach benzynowych mieszanina propanu i butanu?", "LPG", "ciekawostka 1")
        insertData(db, "Język polski", "Jak brzmi w mianowniku liczby mnogiej słowo winorośl?", "Winorośle", "ciekawostka 1")
        insertData(db, "Literatura", "Bohaterami którego utworu Gombrowicza są król Ignacy, Iwona i książe Filip?", "Iwona Księżniczka Burgunda", "ciekawostka 1")

        insertData(db, "Broń", "Jak nazywa się rakieta świetlna zrzucana z samolotu na spadochronie do oświetlenia celu bombardowania?", "Flara", "ciekawostka 1")
        insertData(db, "Kynologia", "Z którego kontynentu wywodzi się pies rasy Amstaff?", "Amstaff wywodzą się z Ameryki Północnej", "ciekawostka 1")
        insertData(db, "Literatura", "Której wojnie światowej dotyczy cykl powieściowy Wielka wojna białych ludzi Arnolda Zweig'a?", "Pierwszej wojnie światowej", "ciekawostka 1")
        insertData(db, "Geografia", "W Polsce mamy góry Pieniny. A w którym państwie są góry Peniny?", "W Wielkiej Brytanii", "ciekawostka 1")
        insertData(db, "Medycyna", "Czy zaburzenie w rozpoznawaniu barw zwane daltonizmem występuje w równym stopniu u kobiet i u mężczyzn?", "Nie, częściej u mężczyzn", "ciekawostka 1")
        insertData(db, "Polityka", "Jaki jest ustrój polityczny Watykanu?", "Monarchia absolutna", "ciekawostka 1")
        insertData(db, "Polska kultura", "Proszę wymienić dwie z siedmiu postaci, które towarzyszą Stanisławowi Wyspiańskiemu na jego krakowskim pomniku.", "Stańczyk, Przybyszewski", "ciekawostka 1")
        insertData(db, "Muzyka", "Śpiewa Carla Bruni, włoska modelka i piosenkarka, żona jednego z byłych prezydentów Francji. Którego?", "Nicolasa Sarkozy'ego", "ciekawostka 1")
        insertData(db, "Geografia", "Na której wyspie jest ziemia Pirri'ego? Od nazwiska zdobywcy bieguna północnego.", "Na Grenlandii", "ciekawostka 1")
        insertData(db, "Film", "Która liczba występuje w tytule filmu Federico Fellini'ego?", "Osiem i pół", "ciekawostka 1")
        insertData(db, "Historia", "Jak nazywał się wierzchowiec Mahometa?", "Alborak albo Alburak", "ciekawostka 1")
        insertData(db, "Jednostki miar", "Cetnar to jednostka długości, objętości czy masy?", "Objętości", "ciekawostka 1")
        insertData(db, "Literatura", "Wydana w 1908 roku powieść Stefana Żeromskiego stała się skandalem literackim. Jaki tytuł nosi ta powieść?", "Dzieje grzechu", "ciekawostka 1")
        insertData(db, "Polityka", "W którym mieście ma siedzibę Parlament Szwajcarii?", "W Bernie", "ciekawostka 1")

        insertData(db, "Historia", "Który cesarz był pierwszym ochrzczonym władcą Rzymu?", "Konstantyn Wielki", "ciekawostka 1")
        insertData(db, "Matematyka", "Geometria. Ile kątów ma dekagon?", "Dziesięć", "ciekawostka 1")
        insertData(db, "Prawo", "Czy udzielając komuś plenipotencji upoważniamy go do działania w naszym imieniu, czy karcimy tę osobę?", "Do działania w naszym imieniu", "ciekawostka 1")
        insertData(db, "Historia", "W którym wieku urodził się Joachim Lelewel, historyk i działacz polityczny?", "W osiemnastym", "ciekawostka 1")
        insertData(db, "Zoologia", "Jak nazywa się rząd ssaków jajorodnych, do których należą kolczatki i dziobaki?", "Stekowce", "ciekawostka 1")
        insertData(db, "Sport", "Klaret jag. To trofeum mistrza golfa, krykieta czy jachtów dwumastowych?", "Mistrza golfa", "ciekawostka 1")
        insertData(db, "Matematyka", "Z którą dziedziną matematyki związane jest pojęcie wariacji?", "Kombinatoryka", "ciekawostka 1")
        insertData(db, "Telewizja", "Kim z wykształcenia był Jan Suzin, speaker telewizyjny związany z telewizją polską przez czterdzieści jeden lat?", "Architektem", "ciekawostka 1")
        insertData(db, "Szkutnictwo", "Nazwa której części stopy jest także nazwą części masztu?", "Pięta", "ciekawostka 1")
        insertData(db, "Literatura", "W którym opowiadaniu Josepha Conrada występują Kurtz i Marlowe?", "Jądro ciemności", "ciekawostka 1")
        insertData(db, "Film", "Na którym festiwalu filmowym przyznawana jest nagroda o nazwie Złota Muszla?", "San Sebastian", "ciekawostka 1")
        insertData(db, "Geografia", "Geografia Polski. W której miejscowości w Pieninach kończy się spływ przełomem Dunajca?", "Szczawnica lub Krościenko", "ciekawostka 1")
        insertData(db, "Historia", "Czy Anna Jagiellonka, córka Władysława Jagiellończyka była królową Polski?", "Nie, nie była królową Polski", "ciekawostka 1")
        insertData(db, "Historia", "Jakie imię nosiła żona Lorda Coventry, która według legendy uwolniła ludność odnałożonej przez męża Daniny, przejeżdżając nago na koniu przez miasto?", "Lady Godiva", "ciekawostka 1")

        insertData(db, "Geografia", "Na terenie którego stanu znajduje się Centrum Lotów Kosmicznych, Kennedy Space Center?", "Floryda", "ciekawostka 1")
        insertData(db, "Geografia", "Jak nazywają się hiszpańskie miasta autonomiczne, pół enklawy w Maroku?", "Ceuta i Melilla", "ciekawostka 1")
        insertData(db, "Język polski", "Miły chłopiec, piękny brzydal, jasny dzień. Które z tych wyrażeń jest oksymoronem?", "Piękny brzydal", "ciekawostka 1")
        insertData(db, "Sztuka", "Co trzyma w ręku chłopiec na obrazie Władysława Podkowińskiego, dzieci w ogrodzie?", "Konewkę do podlewania", "ciekawostka 1")
        insertData(db, "Kulinaria", "Czy jad kiełbasiany, bardzo silna trucizna, może występować w niewłaściwie przygotowanej konserwie jarzynowej?", "Tak", "ciekawostka 1")
        insertData(db, "Historia", "Druga wojna światowa. Dla jakiej grupy jeńców wojennych przeznaczone były niemieckie obozy znane jako oflagi?", "Dla oficerów", "ciekawostka 1")
        insertData(db, "Muzyka", "Czy Jerzy Fryderyk Händel był rówieśnikiem Jana Sebastiana Bacha?", "Tak, obaj urodzili się w 1685 roku", "ciekawostka 1")
        insertData(db, "Sztuka", "Jak nazywa się łańcuszek do zegarka kieszonkowego?", "Deviska", "ciekawostka 1")
        insertData(db, "Mechanika", "Do czego służy pierścień zwany zimmeringiem?", "Do uszczelniania wałków", "ciekawostka 1")
        insertData(db, "Geografia", "Na którym kontynencie wznoszą się góry smocze?", "W Afryce, na południu", "ciekawostka 1")
        insertData(db, "Literatura", "Polska literatura. Pisarze o pseudonimach Alfa, Beta, Gamma i Delta to bohaterowie której książki Czesława Miłosza?", "\"Zniewolony umysł\"", "ciekawostka 1")
        insertData(db, "Historia", "Jakiej narodowości był pisarz Kalimach, nauczyciel synów Kazimierza Jagiellończyka?", "Włoch", "ciekawostka 1")
        insertData(db, "Historia", "Z którego drewna strugano kołki, którymi przebijano serca wampirom?", "Kołki osinowe", "ciekawostka 1")

        insertData(db, "Muzyka", "Kto w XIX wieku skomponował poemat symfoniczny, ucieszne figle Dyla Sowizdrzała?", "Ryszard Strauss", "ciekawostka 1")
        insertData(db, "Geografia", "Czy w Egipcie istnieje Dolina Królowych?", "Tak, to miejsce pochówku żon i dzieci królewskich", "ciekawostka 1")
        insertData(db, "Geografia", "Jak nazywa się szałas pasterzy w Karpatach? Słowo pochodzi z rumuńskiego.", "Koliba albo Koleba", "ciekawostka 1")
        insertData(db, "Historia", "W którym wieku holenderski żeglarz Willem Barends odkrył Spitsbergen?", "W wieku XVI", "ciekawostka 1")
        insertData(db, "Chemia", "Chemia. Mydła to są sole czy estry?", "Sole", "ciekawostka 1")
        insertData(db, "Geografia", "Która wyspa archipelagu Mariany na Oceanie Spokojnym jest największa?", "Wyspa Gułam", "ciekawostka 1")
        insertData(db, "Muzyka", "Kto skomponował cztery Litanie Ostrobramskie?", "Stanisław Moniuszko", "ciekawostka 1")
        insertData(db, "Polityka", "Politycy. Kanclerz to tytuł szefa rządu w dwóch europejskich państwach. W których?", "Niemczech i Austrii", "ciekawostka 1")
        insertData(db, "Geografia", "Czy nad cieśniną Bosfor stoi most łączący Europę z Azją?", "Tak, jest tam most", "ciekawostka 1")
        insertData(db, "Sztuka", "Którą dziedziną sztuki zajmują się Krzysztof Warlikowski, Grzegorz Jarzyna i Wojciech Kościelniak?", "Teatrem, są to reżyserzy teatralni", "ciekawostka 1")
        insertData(db, "Matematyka", "Teraz matematyka. Jeden, dwa i trzy. Która z tych liczb nie jest liczbą pierwszą?", "Jedynka, bo z definicji liczba pierwsza musi być większa od jedności", "ciekawostka 1")
        insertData(db, "Historia", "Kto był założycielem fabryki maszyn rolniczych i narzędzi w Poznaniu w połowie XIX wieku?", "Hipolit Cegielski", "ciekawostka 1")
        insertData(db, "Literatura", "Jak nazywał się autor powieści \"Imię Róży\"?", "Umberto Eco", "ciekawostka 1")
        insertData(db, "Geografia", "W którym mieście jest cmentarz Łyczakowski?", "We Lwowie", "ciekawostka 1")
        insertData(db, "Fizyka", "Żarnik jest elementem żarówki czy żyroskopu?", "Żarówki", "ciekawostka 1")
        insertData(db, "Prawo", "Jak z łaciny nazywa się prawo oparte na zasadzie \"oko za oko, ząb za ząb\"?", "Prawo Talionu", "ciekawostka 1")
        insertData(db, "Fizyka", "Fizyka. 100 stopni Celsjusza. Ile to stopni Kelwina?", "373 stopnie Kelwina", "ciekawostka 1")
        insertData(db, "Film", "Jak nazywał się czeski reżyser, twórca filmów \"Amadeusz\", \"Her\" i \"Lot nad kukułczym gniazdem\"?", "Miloš Forman", "ciekawostka 1")
        insertData(db, "Historia", "W którym wieku powstała Konwencja berneńska, umowa o ochronie dzieł literackich i artystycznych?", "XIX wiek", "ciekawostka 1")
        insertData(db, "Nauka", "Komu po raz pierwszy udało się statycznie skroplić tlen i azot z powietrza?", "Karol Olszewski i Zygmunt Wróblewski", "ciekawostka 1")
        insertData(db, "Polityka", "Jak ma na imię amerykańska pedagog, żona Joe Bidena, pierwsza dama Stanów Zjednoczonych?", "Jill Tracy Biden", "ciekawostka 1")
        insertData(db, "Hymny", "Od jakich słów zaczyna się hymn Związku Harcerstwa Polskiego?", "\"Wszystko co nasze Polsce oddamy\"", "ciekawostka 1")
        insertData(db, "Geografia", "Które państwa łączy Eurotunel?", "Francję z Wielką Brytanią", "ciekawostka 1")

        insertData(db, "Geometria", "Jak nazywa się powierzchnia kuli?", "Sfera", "ciekawostka 1")
        insertData(db, "Mitologia", "Któremu rzymskiemu Bogu poświęcone były dąb, wilk i dzięcioł?", "Marsowi", "ciekawostka 1")
        insertData(db, "Nauka", "Który amerykański naukowiec po tym jak jego dzieło wcielono w życie powiedział \"stałem się śmiercią, niszczycielem światów\"?", "Robert Oppenheimer", "ciekawostka 1")
        insertData(db, "Meteorologia", "W jakim kierunku wieje bryza nocna? Od morza w stronę lądu czy przeciwnie?", "Od lądu do morza", "ciekawostka 1")
        insertData(db, "Językoznawstwo", "Którym czteroliterowym słowem można zastąpić słowo halucynacja?", "Omam", "ciekawostka 1")
        insertData(db, "Botanika", "Koszyczki kwiatowe, których roślin popularnie nazywane są rzepami?", "Koszyczki ostu (lub łopianu)", "ciekawostka 1")
        insertData(db, "Historia", "Który zamek był główną kwaterą powstańczego dowódcy Aleksandra Kostki-Napierskiego?", "Zamek w Czorsztynie", "ciekawostka 1")
        insertData(db, "Nauka", "Jak nazywali się ojciec i córka, którzy w różnych latach dostali Nagrodę Nobla? On z fizyki, ona z chemii.", "Piotr Curie i Irena Joliot-Curie", "ciekawostka 1")
        insertData(db, "Literatura", "Polska literatura. Jak nazywała się utopijna wyspa, na którą trafił Mikołaj Doświadczyński, bohater powieści Krasickiego?", "Wyspa Nipu", "ciekawostka 1")
        insertData(db, "Geografia", "Na którym kontynencie żyją Ujgurzy?", "Azja", "ciekawostka 1")
        insertData(db, "Literatura", "Jak nazywał się jeden z bohaterów tragedii Szekspira, przyjaciel Romea, zabity przez Tybalta?", "Merkucjo (Mercutio)", "ciekawostka 1")
        insertData(db, "Historia", "W którym wieku era panowania japońskiego cesarza Naruhito dostała nazwę Piękna Harmonia?", "XXI (Naruhito objął tron w 2019 roku)", "ciekawostka 1")
        insertData(db, "Geografia", "Z którym polskim miastem łączy się niemiecki Heringsdorf transgraniczną nadmorską promenadą?", "Świnoujście", "ciekawostka 1")
        insertData(db, "Kuchnia", "Zakwas na żur przygotowuje się z mąki z którego zboża?", "Mąki żytniej", "ciekawostka 1")
        insertData(db, "Językoznawstwo", "Jak nazywa się najstarsze pismo słowiańskie utworzone przez Cyryla w drugiej połowie IX wieku?", "Głagolica", "ciekawostka 1")
        insertData(db, "Wojsko", "Który stopień w wojsku polskim jest wyższy od kapitana, niższy od podpułkownika?", "Major", "ciekawostka 1")
    }
}